In [ ]:
# *_*coding:utf-8 *_*
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import csv
import pandas as pd
import numpy as np
import random
from sklearn.svm import SVC,SVR
from sklearn.metrics import confusion_matrix,r2_score,mean_absolute_error,mean_squared_error


path = 'E:/Download/zhenghaiyang-phm-ieee-2012-data-challenge-dataset-master/phm-ieee-2012-data-challenge-dataset/txt/'

# 数据源
# 粒子群算法参数配置
class args:
    W = 0.5 # 惯性权重
    c1 = 0.2 # 局部学习因子
    c2 = 0.5 # 全局学习因子
    n_iterations = 1000 # 迭代步数
    n_particles = 1000 # 粒子数

# SVM配置
kernel = 'rbf' # ["linear","poly","rbf","sigmoid"]


#画图
def plot(position,n):
    x = []
    y = []
    z = []
    for i in range(0,len(position)):
        x.append(position[i][0])
        y.append(position[i][1])
        z.append(position[i][2])
    colors = (0,0,0)
    # plt.scatter(x, y, c = colors, alpha = 0.1)
    # plt.xlabel('C')
    # plt.ylabel('gamma')
    # plt.axis([0,10,0,10])
    # plt.gca().set_aspect('equal', adjustable='box')
    plt.rcParams['font.sans-serif'] = ['SimHei']
    plt.rcParams['axes.unicode_minus'] = False
    # plt.title('当前迭代次数 %d'%n)
    fig = plt.figure()
    ax = plt.axes(projection='3d')
    # ax = fig.add_subplot(111, projection='3d')
    # ax.scatter(x,y,z)
    # ax.set_xlabel('C')
    # ax.set_ylabel('g')
    # ax.set_zlabel('e')
    ax.scatter3D(x, y, z, 'gray')
    ax.set_title('当前迭代次数 %d '%n)

    return plt.show()



#读数据
def data_zhoucheng(data_path):

    x = pd.read_csv(r'E:\Download\pso-svm-master\pso-svm-master\data\x.txt',header=None)
    # x = pd.read_csv(data_path + 'zb6' + '.txt', header=None)
    # x = np.loadtxt(data_path + 'x' + '.txt')
    # y = pd.read_csv(data_path + 'PCAguiyihua' + '.txt',header=None)
    y = np.loadtxt(data_path + 'nengliangshangguiyihua' + '.txt')
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.40)
    return X_train, X_test, y_train, y_test




##主程序
def fitness_function(position,data):
    X_train, X_test, y_train, y_test = data
    svclassifier = SVR(kernel=kernel, gamma = position[0], C = position[1],epsilon=position[2] )
    svclassifier.fit(X_train, y_train)
    y_train_pred = svclassifier.predict(X_train)
    y_test_pred = svclassifier.predict(X_test)
    # return confusion_matrix(y_train,y_train_pred)[0][1] + confusion_matrix(y_train,y_train_pred)[1][0], confusion_matrix(y_test,y_test_pred)[0][1] + confusion_matrix(y_test,y_test_pred)[1][0]
    return mean_squared_error(y_train, y_train_pred),mean_squared_error(y_test, y_test_pred)



def pso_svm(data):
    # 初始化参数
    particle_position_vector = np.array([np.array([random.random() * 10, random.random() * 10, random.random() * 10]) for _ in range(args.n_particles)])
    pbest_position = particle_position_vector
    pbest_fitness_value = np.array([float('inf') for _ in range(args.n_particles)])
    gbest_fitness_value = np.array([float('inf'), float('inf')])
    gbest_position = np.array([float('inf'), float('inf')])
    velocity_vector = ([np.array([0, 0,0]) for _ in range(args.n_particles)])
    iteration = 0

    while iteration < args.n_iterations:
        plot(particle_position_vector,iteration)
        print('################################################################# 当 前 迭 代 次 数 %d #################################################################'%iteration)
        for i in range(args.n_particles):
            fitness_cadidate = fitness_function(particle_position_vector[i], data)
            print("error of particle-", i, "is (training, test)", fitness_cadidate, " At (gamma, c, e): ",
                  particle_position_vector[i])

            if (pbest_fitness_value[i] > fitness_cadidate[1]):
                pbest_fitness_value[i] = fitness_cadidate[1]
                pbest_position[i] = particle_position_vector[i]

            if (gbest_fitness_value[1] > fitness_cadidate[1]):
                gbest_fitness_value = fitness_cadidate
                gbest_position = particle_position_vector[i]
            elif (gbest_fitness_value[1] == fitness_cadidate[1] and gbest_fitness_value[0] > fitness_cadidate[0]):
                gbest_fitness_value = fitness_cadidate
                gbest_position = particle_position_vector[i]

        for i in range(args.n_particles):
            new_velocity = (args.W * velocity_vector[i]) + (args.c1 * random.random()) * (
                        pbest_position[i] - particle_position_vector[i]) + (args.c2 * random.random()) * (
                                       gbest_position - particle_position_vector[i])
            new_position = new_velocity + particle_position_vector[i]
            particle_position_vector[i] = new_position
        print('################################################################# 当 前 迭 代 次 数 %d #################################################################' % iteration)

        iteration = iteration + 1
    print(" Best At (gamma, c, e): ",particle_position_vector[args.n_iterations])


def main():

    X_train, X_test, y_train, y_test = data_zhoucheng(path)
    data = [X_train, X_test, y_train, y_test]
    pso_svm(data)


if __name__ == '__main__':
    main()

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat
import scipy.io as scio
from PyEMD import EMD,CEEMDAN,EEMD
import os
from scipy.io import loadmat
import tensorflow as tf
import os
import sys
from matplotlib import pyplot as plt
from tensorflow.keras.layers import Conv2D, BatchNormalization, Activation, MaxPool2D, Dropout, Flatten, Dense
from tensorflow.keras import Model
import glob
from skimage import transform
from PIL import Image
import skimage
from skimage import io
import numpy as np
import matplotlib.pyplot as plt
from vmdpy import VMD
import pandas as pd
from scipy.fftpack import fft,ifft


d= pd.read_csv('E:\\CAET\\有车\\1-1-2021-12-15-16-34-10.txt')[10:]
d= np.array(d).reshape(1,-1)[0]


alpha = 2000       # moderate bandwidth constraint
tau = 0.            # noise-tolerance (no strict fidelity enforcement)
K =11             # 3 modes
DC = 0             # no DC part imposed
init = 1           # initialize omegas uniformly
tol = 1e-7
#. Run VMD
u, u_hat, omega = VMD(d, alpha, tau, K, DC, init, tol)

import scipy.signal as signal

def bls(y,fs):
    
    y_hht=signal.hilbert(y)#;%希尔伯特变换
    y_an=abs(y_hht)#;%包络信号
    y_an=y_an-np.mean(y_an)#;%去除直流分量
    y_an_nfft= np.log2(len(y_an))#;%包络的DFT的采样点数 取2的幂次方
#     print(y_an_nfft,y_an)
    y_an_ft=np.fft.fft(y_an,int(y_an_nfft))#;%包络的DFT
#     print(len(y_an))
    c=2*abs(y_an_ft[0:int(y_an_nfft/2)])/len(y_an)#;%包络幅值
#     print(c)
    p=c/np.sum(c)
    E = -sum(p*np.log(p))
    return E

# bls(d,fs)



# q = d.kurt()
# print(u.shape)
b = []
Rk = []
for i in range(K):
    R= u[i:]
#     print(R)
    
    R_mean = np.mean(R) #计算均值
    R_var = np.var(R)  #计算方差
    R_ku = np.mean((R - R_mean) ** 4) / pow(R_var, 2) #计算峰度
    Rk.append(-R_ku)
#     R_ku.tolist()
#     print('峭度是%f'%R_ku,type(R_ku))
    fs = 100
    bl=bls(u[i],fs)
    b.append(bl)
#     print('包络熵是%f'%bl)
# print(b,Rk)
# print(min(b),min(Rk))
# print(b.index(min(b)),Rk.index(min(Rk)))
min(b),min(Rk)

(0.34903968067801205, -5.971964301373132)

In [57]:
def P_DTLZ(Operation,Problem,M,Input):
    Boundary = []
    Coding = ""
    k = 7
    K = [5, 10, 10, 10, 10, 10, 20]
    K_select = K[k - 1]
#     print(K_select)
    if Operation == "init":
        D = M + K_select - 1
        MaxValue = np.ones((1, D))
#         print(MaxValue)
        MinValue = np.zeros((1, D))
#         print(MinValue)
        Population = np.random.random((Input, D))
#         print(Population.shape)
        Population = np.multiply(Population, np.tile(MaxValue, (Input, 1))) +\
            np.multiply((1-Population), np.tile(MinValue, (Input, 1)))
#         print(Population)
        Boundary = np.vstack((MaxValue, MinValue))
#         print(Boundary)
        Coding = "Real"
#         print(np.tile(MaxValue, (Input, 1)))
        return Population, Boundary, Coding
    elif Operation == "value":
        Population = Input
        FunctionValue = np.zeros((Population.shape[0], M))
        if Problem == "DTLZ1":
            # g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1, keepdims = True))
            g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1))
            for i in range(M):
                FunctionValue[:, i] = 0.5*np.multiply( np.prod(Population[:, :M-i-1], axis=1), (1+g))
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], 1-Population[:, M-i-1])
        elif Problem == "DTLZ2":
            g = np.sum( (Population[:, M-1:] - 0.5)**2,axis=1)
            for i in range(M):
                FunctionValue[:, i] = (1+g)*np.prod( np.cos( 0.5*np.pi*(Population[:, :M-i-1]) ),axis=1 )
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], np.sin( 0.5*np.pi* ( Population[:, M-i-1]) ) )

                    
# [Output, Boundary, Coding] = P_DTLZ('init', "DTLZ1", 2, 10)
# print(Output, Boundary, Coding)
def P_objective(Operation,Problem,M,Input):
    [Output, Boundary, Coding] = P_DTLZ('init', "DTLZ1", 2, 10)
    if Boundary == []:
        return Output
    else:
        return Output, Boundary, Coding
    
fitness_ = P_objective("value", "DTLZ2", 2, 10)
print(fitness_,fitness_[2])

(array([[0.40526426, 0.0156696 , 0.94385518, 0.44350696, 0.74482759,
        0.44252966, 0.81907023, 0.58587606, 0.68546647, 0.15945388,
        0.76508006, 0.52425135, 0.30539089, 0.60338437, 0.79855947,
        0.43022325, 0.40265749, 0.47005067, 0.18628259, 0.14952739,
        0.63234445],
       [0.91509393, 0.01801736, 0.01557493, 0.28626524, 0.82949222,
        0.41101138, 0.90219065, 0.75551269, 0.7041951 , 0.83266056,
        0.95740856, 0.72388439, 0.78993708, 0.13481124, 0.71124025,
        0.46516391, 0.59516529, 0.60751897, 0.11995168, 0.07254348,
        0.12394161],
       [0.13384108, 0.82076023, 0.96292286, 0.00126306, 0.522647  ,
        0.84969303, 0.26960998, 0.93140259, 0.32816814, 0.58517332,
        0.72416511, 0.82598126, 0.34218836, 0.77092271, 0.29109617,
        0.07664731, 0.12693911, 0.40198024, 0.45216334, 0.77238867,
        0.90217147],
       [0.25424831, 0.85718144, 0.9305465 , 0.52198741, 0.07336634,
        0.36142241, 0.38998382, 0.54704156, 0.648044

C:\Users\工作站2\AppData\Local\Temp/ipykernel_4968/2689522081.py:46: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if Boundary == []:


In [2]:
import random
def init_designparams(particals,in_min,in_max):
	in_dim = len(in_max) 	#输入参数的维度
# 	print(in_dim)
	in_temp = np.zeros((particals,in_dim))
	for i in range(particals):
		for j in range(in_dim):
			in_temp[i,j] = random.uniform(0,1)*(in_max[j]-in_min[j])+in_min[j]
	return in_temp
# init_designparams(10,np.array([0, 0]),np.array([10, 10]))
# print(np.array([10, 10]))
in_ =init_designparams(10,np.array([0, 0]),np.array([10, 10]))
print(in_)
fitness_curr = []
def fitness_(in_):
    degree_45 = ((in_[0]-in_[1])**2/2)**0.5
    degree_135 = ((in_[0]+in_[1])**2/2)**0.5
    print(degree_45,degree_135)
    fit_1 = 1-np.exp(-(degree_45)**2/0.5)*np.exp(-(degree_135-np.sqrt(200))**2/250)
    fit_2 = 1-np.exp(-(degree_45)**2/5)*np.exp(-(degree_135)**2/350)
    return [fit_1,fit_2]


for i in range((in_).shape[0]):
    fitness_curr.append(fitness_(in_[i]))
#     print(fitness_(in_[i]))
# print(np.array(fitness_curr))
# self.fitness_ = np.array(fitness_curr) #适应值

[[5.72687268 3.98970089]
 [6.10194488 7.18173698]
 [1.55681936 7.30917837]
 [5.24209184 1.41808737]
 [9.11299401 2.66383167]
 [2.63831053 8.44854863]
 [9.89999275 6.8271866 ]
 [8.45417519 5.24885446]
 [8.42522363 6.01180494]
 [1.21002565 4.82528936]]
1.2283659573133214 6.8706550607885495
0.7635283111943856 9.392981521288057
4.067532068612356 6.269207115846015
2.7039794950396607 4.709457886547
4.560246421594845 8.32747330065842
4.108458760032466 7.8395932968703645
2.1728020595830464 11.82790194868728
2.2665040275099 9.68950518745113
1.7065447255667794 10.208520799160585
2.55637747959514 4.267612168979045


# mopso

In [61]:
MaxValue = np.ones((1, 2))*20
MinValue = np.ones((1, 2))*-20
# np.tile(MaxValue, (5, 1))
# Population = np.random.random((5, 6))
# np.multiply((1 - Population), np.tile(MinValue, (5, 1)))
# print(Population)
# in_temp = np.random.uniform(0,1,(5,6))
# in_temp
Boundary = np.vstack((MaxValue, MinValue))
Boundary

array([[ 20.,  20.],
       [-20., -20.]])

In [31]:
def P_objective(Operation,Problem,M,Input):
    [Output, Boundary, Coding] = P_DTLZ(Operation, Problem, M, Input)
    if Boundary == []:
        return Output
    else:
        return Output, Boundary, Coding

def P_DTLZ(Operation,Problem,M,Input):
    Boundary = []
    Coding = ""
    k = 1
    K = [5, 10, 10, 10, 10, 10, 20]
    K_select = K[k - 1]
    if Operation == "init":
        D = M + K_select - 1
        MaxValue = np.ones((1, D))
        MinValue = np.zeros((1, D))
        Population = np.random.random((Input, D))
        Population = np.multiply(Population, np.tile(MaxValue, (Input, 1))) +\
            np.multiply((1-Population), np.tile(MinValue, (Input, 1)))
        Boundary = np.vstack((MaxValue, MinValue))
        Coding = "Real"
        return Population, Boundary, Coding
    elif Operation == "value":
        Population = Input
        FunctionValue = np.zeros((Population.shape[0], M))
        if Problem == "DTLZ1":
            # g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1, keepdims = True))
            g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1))
            for i in range(M):
                FunctionValue[:, i] = 0.5*np.multiply( np.prod(Population[:, :M-i-1], axis=1), (1+g))
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], 1-Population[:, M-i-1])
        elif Problem == "DTLZ2":
            g = np.sum( (Population[:, M-1:] - 0.5)**2,axis=1)
            for i in range(M):
                FunctionValue[:, i] = (1+g)*np.prod( np.cos( 0.5*np.pi*(Population[:, :M-i-1]) ),axis=1 )
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], np.sin( 0.5*np.pi* ( Population[:, M-i-1]) ) )


#         elif Operation =="VMD":

#             d = pd.read_csv('E:\\CAET\\有车\\1-1-2021-12-15-16-34-10.txt')[10:]
#             d = np.array(d).reshape(1, -1)[0]


#             alpha = 2000  # moderate bandwidth constraint
#             tau = 0.  # noise-tolerance (no strict fidelity enforcement)
#             K = 11  # 3 modes
#             DC = 0  # no DC part imposed
#             init = 1  # initialize omegas uniformly
#             tol = 1e-7
#             # . Run VMD
#             u, u_hat, omega = VMD(d, alpha, tau, K, DC, init, tol)


        return FunctionValue, Boundary, Coding


P_objective("value", "DTLZ1", 2, in_temp)

array([[176.12358962,  53.71800321],
       [111.43871673,  99.92600015],
       [ 19.02240127, 285.96331077],
       [150.82782348, 163.51980251],
       [ 57.14222521, 108.22375232]])

In [10]:
import numpy as np
from vmdpy import VMD
import pandas as pd
import scipy.signal as signal

def P_objective(Operation,Problem,M,Input):
    [Output, Boundary, Coding] = P_DTLZ(Operation, Problem, M, Input)
    if Boundary == []:
        return Output
    else:
        return Output, Boundary, Coding

def P_DTLZ(Operation,Problem,M,Input):
    Boundary = []
    Coding = ""
    FunctionValue = []
    k = 1
    K = [5, 10, 10, 10, 10, 10, 20]
    K_select = K[k - 1]
    if Operation == "init":
        D = 2
        MaxValue = np.ones((1, D))*10
        MinValue = np.ones((1, D))*-10
        x = []
        for i in range(1, 10, 2):
            for j in range(500, 3000, 10):
                x.append([i, j])
        x = np.array(x)

        Population = x

        Boundary = np.vstack((MaxValue, MinValue))
        Coding = "Real"
        return Population, Boundary, Coding
    elif Operation == "value":
        x = []
        for i in range(1, 10, 2):
            for j in range(500, 3000, 10):
                x.append([i, j])
        x = np.array(x)

        Population = x
        # Population = Input
        # FunctionValue = np.zeros((Population.shape[0], 2))
        if Problem == "DTLZ1":
            # g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1, keepdims = True))
            g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1))
            for i in range(M):
                FunctionValue[:, i] = 0.5*np.multiply( np.prod(Population[:, :M-i-1], axis=1), (1+g))
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], 1-Population[:, M-i-1])
        elif Problem == "DTLZ2":
            g = np.sum( (Population[:, M-1:] - 0.5)**2,axis=1)
            for i in range(M):
                FunctionValue[:, i] = (1+g)*np.prod( np.cos( 0.5*np.pi*(Population[:, :M-i-1]) ),axis=1 )
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], np.sin( 0.5*np.pi* ( Population[:, M-i-1]) ) )


        elif Operation =="VMD":

            # FunctionValue = []

            d = pd.read_csv('E:\\CAET\\有车\\1-1-2021-12-15-16-34-10.txt')[10:]
            d = np.array(d).reshape(1, -1)[0]

            for i in range(len(Population)):

                alpha = Population[i,:][1]   # moderate bandwidth constraint
                tau = 0.  # noise-tolerance (no strict fidelity enforcement)
                K = Population[i,:][0]  # 3 modes
                DC = 0  # no DC part imposed
                init = 1  # initialize omegas uniformly
                tol = 1e-7
                # . Run VMD
                u, u_hat, omega = VMD(d, alpha, tau, K, DC, init, tol)

                def bls(y, fs):

                    y_hht = signal.hilbert(y)  # ;%希尔伯特变换
                    y_an = abs(y_hht)  # ;%包络信号
                    y_an = y_an - np.mean(y_an)  # ;%去除直流分量
                    y_an_nfft = np.log2(len(y_an))  # ;%包络的DFT的采样点数 取2的幂次方
                    #     print(y_an_nfft,y_an)
                    y_an_ft = np.fft.fft(y_an, int(y_an_nfft))  # ;%包络的DFT
                    #     print(len(y_an))
                    c = 2 * abs(y_an_ft[0:int(y_an_nfft / 2)]) / len(y_an)  # ;%包络幅值
                    #     print(c)
                    p = c / np.sum(c)
                    E = -sum(p * np.log(p))
                    return E

                # bls(d,fs)

                # q = d.kurt()
                # print(u.shape)
                b = []
                Rk = []
                for i in range(K):
                    R = u[i:]
                    #     print(R)

                    R_mean = np.mean(R)  # 计算均值
                    R_var = np.var(R)  # 计算方差
                    R_ku = np.mean((R - R_mean) ** 4) / pow(R_var, 2)  # 计算峰度
                    Rk.append(-R_ku)
                    #     R_ku.tolist()
                    #     print('峭度是%f'%R_ku,type(R_ku))
                    fs = 100
                    bl = bls(u[i], fs)
                    b.append(bl)
                aaa = min(b),min(Rk)
                print(aaa)
                FunctionValue.append(aaa)
#                 FunctionValue =np.array(FunctionValue)

    return FunctionValue, Boundary, Coding

in_=0
P_objective("value", "VMD", 2, in_)

TypeError: cannot unpack non-iterable NoneType object

In [15]:
        x = []
        for i in range(1, 10, 5):
            for j in range(500, 3000, 1000):
                x.append([i, j])
        x = np.array(x)

        x.shape
FrontNO = np.inf*np.ones((1, 6))
np.sum(FrontNO < np.inf)        

0

In [121]:
fitness_.shape
fitness_[0].shape

(2,)

In [122]:
D = 2
MaxValue = np.ones((1, D))
MinValue = np.ones((1, D))


Boundary = np.vstack((MaxValue, MinValue))
in_max = Boundary[0]
in_min = Boundary[1]
    
    
in_dim = len(in_max)     #输入参数维度

in_temp = np.random.uniform(0,1,(particals,in_dim))*(in_max-in_min)+in_min
in_temp.shape

(100, 2)

In [2]:
import numpy as np
from vmdpy import VMD
import pandas as pd
import scipy.signal as signal

def P_objective(Operation,Problem,M,Input):
    [Output, Boundary, Coding] = P_DTLZ(Operation, Problem, M, Input)
    if Boundary == []:
        return Output
    else:
        return Output, Boundary, Coding

def P_DTLZ(Operation,Problem,M,Input):
    Boundary = []
    Coding = ""
    FunctionValue = []
    k = 1
    K = [5, 10, 10, 10, 10, 10, 20]
    K_select = K[k - 1]
    if Operation == "init":
        D = 2
        MaxValue = np.ones((1, D))*10
        MinValue = np.ones((1, D))*-10
        x = []
        for i in range(1, 10, 2):
            for j in range(500, 3000, 10):
                x.append([i, j])
        x = np.array(x)

        Population = x

        Boundary = np.vstack((MaxValue, MinValue))
        Coding = "Real"
        return Population, Boundary, Coding
    elif Operation == "value":
        x = []
        for i in range(1, 10, 5):
            for j in range(500, 3000, 1000):
                x.append([i, j])
        x = np.array(x)

        Population = x
        # Population = Input
        # FunctionValue = np.zeros((Population.shape[0], 2))
        if Problem == "DTLZ1":
            # g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1, keepdims = True))
            g = 100*(K_select+np.sum( (Population[:, M-1:] - 0.5)**2 - np.cos(20*np.pi*(Population[:, M-1:] - 0.5)), axis=1))
            for i in range(M):
                FunctionValue[:, i] = 0.5*np.multiply( np.prod(Population[:, :M-i-1], axis=1), (1+g))
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], 1-Population[:, M-i-1])
        elif Problem == "DTLZ2":
            g = np.sum( (Population[:, M-1:] - 0.5)**2,axis=1)
            for i in range(M):
                FunctionValue[:, i] = (1+g)*np.prod( np.cos( 0.5*np.pi*(Population[:, :M-i-1]) ),axis=1 )
                if i>0:
                    FunctionValue[:, i] = np.multiply(FunctionValue[:, i], np.sin( 0.5*np.pi* ( Population[:, M-i-1]) ) )


        elif Problem =="VMD":

            # FunctionValue = []

            d = pd.read_csv('E:\\CAET\\有车\\1-1-2021-12-15-16-34-10.txt')[10:]
            d = np.array(d).reshape(1, -1)[0]

            for i in range(len(Population)):

                alpha = Population[i,:][1]   # moderate bandwidth constraint
                tau = 0.  # noise-tolerance (no strict fidelity enforcement)
                K = Population[i,:][0]  # 3 modes
                DC = 0  # no DC part imposed
                init = 1  # initialize omegas uniformly
                tol = 1e-7
                # . Run VMD
                u, u_hat, omega = VMD(d, alpha, tau, K, DC, init, tol)

                def bls(y, fs):

                    y_hht = signal.hilbert(y)  # ;%希尔伯特变换
                    y_an = abs(y_hht)  # ;%包络信号
                    y_an = y_an - np.mean(y_an)  # ;%去除直流分量
                    y_an_nfft = np.log2(len(y_an))  # ;%包络的DFT的采样点数 取2的幂次方
                    #     print(y_an_nfft,y_an)
                    y_an_ft = np.fft.fft(y_an, int(y_an_nfft))  # ;%包络的DFT
                    #     print(len(y_an))
                    c = 2 * abs(y_an_ft[0:int(y_an_nfft / 2)]) / len(y_an)  # ;%包络幅值
                    #     print(c)
                    p = c / np.sum(c)
                    E = -sum(p * np.log(p))
                    return E

                # bls(d,fs)

                # q = d.kurt()
                # print(u.shape)
                b = []
                Rk = []
                for i in range(K):
                    R = u[i:]
                    #     print(R)

                    R_mean = np.mean(R)  # 计算均值
                    R_var = np.var(R)  # 计算方差
                    R_ku = np.mean((R - R_mean) ** 4) / pow(R_var, 2)  # 计算峰度
                    Rk.append(-R_ku)
                    #     R_ku.tolist()
                    #     print('峭度是%f'%R_ku,type(R_ku))
                    fs = 100
                    bl = bls(u[i], fs)
                    b.append(bl)
                aaa = min(b),min(Rk)
                FunctionValue.append(aaa)
    FunctionValue =np.array(FunctionValue)

    return FunctionValue, Boundary, Coding






in_ = 10

P_objective("value", "VMD", 2, in_)

array([[ 1.33694804, -2.76698478],
       [ 1.37637129, -2.78602333],
       [ 1.2633603 , -2.77311838],
       [ 0.39574283, -4.85488377],
       [ 0.95825889, -4.61993042],
       [ 0.79886482, -4.61899961]])

In [92]:
in_ = np.array([[-5.28262349 , 8.16826872],[-6.34004699  ,0.20547114],
 [-2.61049839 , 0.47760252],
 [-2.61180659  ,0.80577396],
 [ 0.54494983 ,-0.8525479 ],
 [-6.96574193, -1.35876027]])
fitness_ = np.array([[ 1.33694804 ,-2.76698478],
 [ 1.37637129 ,-2.78602333],
 [ 1.2633603 , -2.77311838],
 [ 0.39574283, -4.85488377],
 [ 0.95825889, -4.61993042],
 [ 0.79886482 ,-4.61899961]])
in_pbest = np.array([[-5.28262349 , 8.16826872],
 [-6.34004699 , 0.20547114],
 [-2.61049839 , 0.47760252],
 [-2.61180659  ,0.80577396],
 [ 0.54494983, -0.8525479 ],
 [-6.96574193 ,-1.35876027]])

out_pbest = np.array([[-2.61180659 , 0.80577396],
 [-2.61180659 , 0.80577396],
 [-2.61180659 , 0.80577396],
 [-2.61180659  ,0.80577396],
 [-2.61180659 , 0.80577396],
 [-2.61180659 , 0.80577396]])

def update_pbest(in_,fitness_,in_pbest,out_pbest):
    temp = out_pbest - fitness_
    print('temp',temp)
    Dominate = np.int64(np.any(temp< 0, axis=1)) - np.int64(np.any(temp> 0, axis=1))
    
    print('Dominate',Dominate)
    remained_1 = Dominate==-1
    print('remained_1',remained_1)
    out_pbest[remained_1] = fitness_[remained_1]
    print('fitness_[remained_1]',fitness_[remained_1])
    print(out_pbest[remained_1])
    in_pbest[remained_1] = in_[remained_1]
    print(in_pbest[remained_1])
    
    remained_2 = Dominate == 0
    print('remained_2',remained_2)
    remained_temp_rand = np.random.rand(len(Dominate),)<0.5
    print('remained_temp_rand',remained_temp_rand)
    print(np.random.rand(len(Dominate),)<0.5)
    remained_final = remained_2 & remained_temp_rand
    print(remained_final)
    out_pbest[remained_final] = fitness_[remained_final]
    print('fitness_[remained_final]',fitness_[remained_final])
    print('out_pbest[remained_final]',out_pbest[remained_final])
    in_pbest[remained_final] = in_[remained_final]
    print('in_[remained_final]',in_[remained_final])
    return in_pbest,out_pbest
update_pbest(in_,fitness_,in_pbest,out_pbest)
# print(temp)

temp [[-3.94875463  3.57275874]
 [-3.98817788  3.59179729]
 [-3.87516689  3.57889234]
 [-3.00754942  5.66065773]
 [-3.57006548  5.42570438]
 [-3.41067141  5.42477357]]
Dominate [0 0 0 0 0 0]
remained_1 [False False False False False False]
fitness_[remained_1] []
[]
[]
remained_2 [ True  True  True  True  True  True]
remained_temp_rand [False  True  True False False  True]
[False  True False False False  True]
[False  True  True False False  True]
fitness_[remained_final] [[ 1.37637129 -2.78602333]
 [ 1.2633603  -2.77311838]
 [ 0.79886482 -4.61899961]]
out_pbest[remained_final] [[ 1.37637129 -2.78602333]
 [ 1.2633603  -2.77311838]
 [ 0.79886482 -4.61899961]]
in_[remained_final] [[-6.34004699  0.20547114]
 [-2.61049839  0.47760252]
 [-6.96574193 -1.35876027]]


(array([[-5.28262349,  8.16826872],
        [-6.34004699,  0.20547114],
        [-2.61049839,  0.47760252],
        [-2.61180659,  0.80577396],
        [ 0.54494983, -0.8525479 ],
        [-6.96574193, -1.35876027]]),
 array([[-2.61180659,  0.80577396],
        [ 1.37637129, -2.78602333],
        [ 1.2633603 , -2.77311838],
        [-2.61180659,  0.80577396],
        [-2.61180659,  0.80577396],
        [ 0.79886482, -4.61899961]]))

In [91]:
in_ = np.array([[-5.28262349 , 8.16826872],[-6.34004699  ,0.20547114],
 [-2.61049839 , 0.47760252],
 [-2.61180659  ,0.80577396],
 [ 0.54494983 ,-0.8525479 ],
 [-6.96574193, -1.35876027]])
fitness_ = np.array([[ 1.33694804 ,-2.76698478],
 [ 1.37637129 ,-2.78602333],
 [ 1.2633603 , -2.77311838],
 [ 0.39574283, -4.85488377],
 [ 0.95825889, -4.61993042],
 [ 0.79886482 ,-4.61899961]])
in_pbest = np.array([[-5.28262349 , 8.16826872],
 [-6.34004699 , 0.20547114],
 [-2.61049839 , 0.47760252],
 [-2.61180659  ,0.80577396],
 [ 0.54494983, -0.8525479 ],
 [-6.96574193 ,-1.35876027]])

out_pbest = np.array([[-2.61180659 , 0.80577396],
 [-2.61180659 , 0.80577396],
 [-2.61180659 , 0.80577396],
 [-2.61180659  ,0.80577396],
 [-2.61180659 , 0.80577396],
 [-2.61180659 , 0.80577396]])
# np.any(temp< 0)
# np.any(temp> 0)
# np.int64(np.any(temp< 0, axis=1))
# np.any(temp< 0, axis=1)
# np.int64(np.any(temp> 0))
# np.int64(True)
temp = out_pbest - fitness_
print(temp)
# np.any(temp< 0)
np.int64(np.any(temp< 0, axis=1))
np.int64(np.any(temp> 0, axis=1))

[[-3.94875463  3.57275874]
 [-3.98817788  3.59179729]
 [-3.87516689  3.57889234]
 [-3.00754942  5.66065773]
 [-3.57006548  5.42570438]
 [-3.41067141  5.42477357]]


array([1, 1, 1, 1, 1, 1], dtype=int64)

In [110]:
import random
k = random.randint(0,9)
a = random.randint(500,4000)
q = []
for i in range(10):
    k = random.randint(0,9)
    a = random.randint(500,4000)
    s = [k,a]
    q.append(s)
    print(s)
q

[2, 1832]
[4, 2162]
[4, 2839]
[6, 3974]
[9, 814]
[8, 523]
[6, 2122]
[7, 2528]
[9, 916]
[6, 758]


[[2, 1832],
 [4, 2162],
 [4, 2839],
 [6, 3974],
 [9, 814],
 [8, 523],
 [6, 2122],
 [7, 2528],
 [9, 916],
 [6, 758]]

In [157]:
import pandas as pd
Population = np.array(q)
d = pd.read_csv('E:\\CAET\\有车\\1-1-2021-12-15-16-34-10.txt')[10:]
d = np.array(d).reshape(1, -1)[0]
b = []
Rk = []
for i in range(2):

    alpha = Population[i,:][1]   # moderate bandwidth constraint
    tau = 0.  # noise-tolerance (no strict fidelity enforcement)
    K = Population[i,:][0]  # 3 modes
    DC = 0  # no DC part imposed
    init = 1  # initialize omegas uniformly
    tol = 1e-7
    # . Run VMD
    u, u_hat, omega = VMD(d, alpha, tau, K, DC, init, tol)
    
    def bls(y, fs):

        y_hht = signal.hilbert(y)  # ;%希尔伯特变换
        y_an = abs(y_hht)  # ;%包络信号
        y_an = y_an - np.mean(y_an)  # ;%去除直流分量
        y_an_nfft = np.log2(len(y_an))  # ;%包络的DFT的采样点数 取2的幂次方
        #     print(y_an_nfft,y_an)
        y_an_ft = np.fft.fft(y_an, int(y_an_nfft))  # ;%包络的DFT
        #     print(len(y_an))
        c = 2 * abs(y_an_ft[0:int(y_an_nfft / 2)]) / len(y_an)  # ;%包络幅值
        #     print(c)
        p = c / np.sum(c)
        E = -sum(p * np.log(p))
        return E


    
    for j in range(K):
        R = u[j:]
        #     print(R)

        R_mean = np.mean(R)  # 计算均值
        R_var = np.var(R)  # 计算方差
        R_ku = np.mean((R - R_mean) ** 4) / pow(R_var, 2)  # 计算峰度
        Rk.append(-R_ku)
        #     R_ku.tolist()
        #     print('峭度是%f'%R_ku,type(R_ku))
        fs = 100
        bl = bls(u[i], fs)
        b.append(bl)
#         f.append([bl,-R_ku])
#         print(b,Rk)
print('*****************************************************')
B = np.array(b).reshape(-1,1)
RK = np.array(Rk).reshape(-1,1)
print(b,Rk)
f = np.hstack((B,RK))
ind = np.lexsort((b,Rk))
print(ind)
print(f[ind[-1]])
# print([b,Rk][ind[-1]])

*****************************************************
[1.1446663789904639, 1.1446663789904639, 0.4966604525876649, 0.4966604525876649, 0.4966604525876649, 0.4966604525876649] [-3.705264044809203, -3.9414017618107273, -3.8274761080375477, -3.6287221141244372, -3.2464976082038, -3.151163909610448]
[1 2 0 3 4 5]
[ 0.49666045 -3.15116391]


In [37]:
N = 5
FrontNO = np.inf*np.ones((1, N))
FrontNO
np.sum(FrontNO < np.inf)
MaxFNO = 0

In [38]:
Matrix = [[   4 ,2763],
 [   7, 3520],
 [  12, 1550],
 [  12  ,892],
 [   7 , 661]]
PopObj = [[   4 ,2763],
 [   7, 3520],
 [  12, 1550],
 [  12  ,892],
 [   7 , 661]]
Matrix = np.array(Matrix )
PopObj = np.array(PopObj )
Matrix_temp = Matrix[:, ::-1]
print(Matrix_temp)
Matrix_row = Matrix_temp.T
print(Matrix_row)
rank = np.lexsort(Matrix_row)
print(np.lexsort(Matrix_row))
Sorted_Matrix = Matrix[rank,:]
print(Sorted_Matrix)


[[2763    4]
 [3520    7]
 [1550   12]
 [ 892   12]
 [ 661    7]]
[[2763 3520 1550  892  661]
 [   4    7   12   12    7]]
[0 4 1 3 2]
[[   4 2763]
 [   7  661]
 [   7 3520]
 [  12  892]
 [  12 1550]]


In [40]:
Remain_Num = 5
M = 2
while (np.sum(FrontNO < np.inf) < Remain_Num) :
    MaxFNO += 1
    for i in range(N):
#         print('FrontNO',FrontNO)
        print(i)
        if FrontNO[0, i] == np.inf:
#             print(FrontNO)
            Dominated = False
            for j in range(i-1, -1, -1):
                if FrontNO[0, j] == MaxFNO:
                    m=2
                    while (m <= M) and (PopObj[i, m-1] >= PopObj[j, m-1]):
                        m += 1
                    Dominated = m > M
                    if Dominated or (M == 2):
                        break
            if not Dominated:
                FrontNO[0,i] = MaxFNO
                
# print('FrontNO',FrontNO)

In [28]:
Dominated = False
print(not Dominated,1)

True 1


In [55]:
N = 5
FrontNO = np.inf*np.ones((1, N))
MaxFNO = 0
Matrix = [[   4 ,2763],
 [   7, 3520],
 [  12, 1550],
 [  12  ,892],
 [   7 , 661]]
PopObj = [[   4 ,2763],
 [   7, 3520],
 [  12, 1550],
 [  12  ,892],
 [   7 , 661]]
Matrix = np.array(Matrix )
PopObj = np.array(PopObj )
Matrix_temp = Matrix[:, ::-1]
print(Matrix_temp)
Matrix_row = Matrix_temp.T
print(Matrix_row)
rank = np.lexsort(Matrix_row)
print(np.lexsort(Matrix_row))
Sorted_Matrix = Matrix[rank,:]
print(Sorted_Matrix)

while (np.sum(FrontNO < np.inf) < Remain_Num) :
    MaxFNO += 1
    print('MaxFNO11',MaxFNO)
    for i in range(N):
        print('i',i)
        print('FrontNOi',FrontNO)
        if FrontNO[0, i] == np.inf:
            print('FrontNO',FrontNO)
            Dominated = False
            print(Dominated)
            for j in range(i-1, -1, -1):
                print('j',j,'MaxFNO',MaxFNO)
                if FrontNO[0, j] == MaxFNO:
                    print('FrontNOj',FrontNO)
                    m=2
                    while (m <= M) and (PopObj[i, m-1] >= PopObj[j, m-1]):
                        print('PopObj[i, m-1] >= PopObj[j, m-1]',PopObj[i, m-1],PopObj[j, m-1])
                        m += 1
                    Dominated = m > M
                    if Dominated or (M == 2):
                        break
            if not Dominated:
                FrontNO[0,i] = MaxFNO

[[2763    4]
 [3520    7]
 [1550   12]
 [ 892   12]
 [ 661    7]]
[[2763 3520 1550  892  661]
 [   4    7   12   12    7]]
[0 4 1 3 2]
[[   4 2763]
 [   7  661]
 [   7 3520]
 [  12  892]
 [  12 1550]]
MaxFNO11 1
i 0
FrontNOi [[inf inf inf inf inf]]
FrontNO [[inf inf inf inf inf]]
False
i 1
FrontNOi [[ 1. inf inf inf inf]]
FrontNO [[ 1. inf inf inf inf]]
False
j 0 MaxFNO 1
FrontNOj [[ 1. inf inf inf inf]]
PopObj[i, m-1] >= PopObj[j, m-1] 3520 2763
i 2
FrontNOi [[ 1. inf inf inf inf]]
FrontNO [[ 1. inf inf inf inf]]
False
j 1 MaxFNO 1
j 0 MaxFNO 1
FrontNOj [[ 1. inf inf inf inf]]
i 3
FrontNOi [[ 1. inf  1. inf inf]]
FrontNO [[ 1. inf  1. inf inf]]
False
j 2 MaxFNO 1
FrontNOj [[ 1. inf  1. inf inf]]
i 4
FrontNOi [[ 1. inf  1.  1. inf]]
FrontNO [[ 1. inf  1.  1. inf]]
False
j 3 MaxFNO 1
FrontNOj [[ 1. inf  1.  1. inf]]
MaxFNO11 2
i 0
FrontNOi [[ 1. inf  1.  1.  1.]]
i 1
FrontNOi [[ 1. inf  1.  1.  1.]]
FrontNO [[ 1. inf  1.  1.  1.]]
False
j 0 MaxFNO 2
i 2
FrontNOi [[1. 2. 1. 1. 1.]]
i 3
F

In [3]:
np.random.rand(1,1)

array([[0.39799891]])